hitbox:
   enabled: true
   lenience: 0.6
   cancel: true
   max_dist: 2.6
   min_vl: 1
   thresholds:
      8: "aacstaffnotify {player} in {world} is suspected for Killaura (Hitbox) (ping = {ping}, tps = {tps})"
      20: "aacstaffnotify {player} in {world} is suspected for Killaura (Hitbox) #2 (ping = {ping}, tps = {tps})"
      50: "aacstaffnotify {player} in {world} is suspected for Killaura (Hitbox) #3 (ping = {ping}, tps = {tps})"

badpackets:
   enabled: true
   cancel_threshold: 30
   max_moves: 10
   thresholds:
      90: "aacstaffnotify {player} in {world} is trying to speed up time (ping = {ping}, tps = {tps})"
      150: "ba kick {player} gwen &4&lGWEN&c: Suspicious activity"
      250: "ba kick {player} gwen &4&lGWEN&c: badpackets"
   
criticals:
   enabled: true
   cancel_false_hit: true
   jump_delay: 5
   thresholds:
      3: "aacstaffnotify {player} in {world} is suspected for Criticals (ping = {ping}, tps = {tps})"
      10: "ba kick {player} gwen &4&lGWEN&c: Incorrect movement (Criticals hacking?) Warning 1"
      25: "ba kick {player} gwen &4&lGWEN&c: Incorrect movement (Criticals hacking?) Warning 2"
      50: "ba kick {player} gwen &4&lGWEN&c: Incorrect movement (Criticals hacking?) Last warning"

fastbow:
   enabled: true
   lenience_ms: 130
   block_ticks: 100
   thresholds:
      3: "aacstaffnotify {player} in {world} is suspected for FastBow (ping = {ping}, tps = {tps})"
      10: "ba kick {player} gwen &4&lGWEN&c: Shooting arrows too quickly. Warning 1"
      50: "ba kick {player} gwen &4&lGWEN&c: Shooting arrows too quickly. Last warning"
      50: "ba ban {player} gwen &4&lGWEN&c: Hacking - FastBow"

fightspeed:
   enabled: true
   max_hits_per_second: 19
   max_interact_per_second: 50
   consistent_check: true
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for AutoClicker (FightSpeed) (ping = {ping}, tps = {tps})"
      25: "ba kick {player} gwen &4&lGWEN&c: Strange click speed. (AutoClicker? Macros?)"
      50: "ba kick {player} gwen &4&lGWEN&c: Strange click speed. (AutoClicker? Macros?)"
      75: "ba kick {player} gwen &4&lGWEN&c: Strange click speed. (AutoClicker? Macros?)"
      100: "ba ban {player} gwen &4&lGWEN&c: Strange click speed. (AutoClicker? Macros?)"

fly:
   enabled: true
   tolerance: 0.015
   e_tolerance: 0.2
   vl_multiplier: 6.0
   min_vl: 28
   vel_ticks: 30
   teleport: true
   abilities: true
   reduce_delay: 20
   reset_pitch: false
   thresholds:
      120: "aacstaffnotify {player} in {world} is suspected for Fly (ping = {ping}, tps = {tps})"
      210: "aacstaffnotify {player} in {world} is suspected for Fly #2 (ping = {ping}, tps = {tps}"
      300: "ba kick {player} gwen &4&lGWEN&c: Moved unexpectedly"
      500: "ba kick {player} gwen &4&lGWEN&c: Fly Hacking"
      1000: "ba ban {player} gwen &4&lGWEN&c: Fly Hacking"

speed:
   enabled: true
   threshold: 0.005
   vel_ticks: 30
   vl_multiplier: 6.0
   max_sneak_toggles: 15
   max_use_toggles: 35
   min_vl: 36
   reduce_delay: 20
   thresholds:
      60: "aacmessage {player} It looks like you might be glitching, please tap sneak and block with your sword"
      150: "aacstaffnotify {player} in {world} is suspected for Speed hacking (ping = {ping}, tps = {tps})"
      210: "ba kick {player} gwen &4&lGWEN&c: Moved too quickly"
      500: "ba kick {player} gwen &4&lGWEN&c: Moved too quickly. Speedhack, flight"
      1000: "ba ban {player} gwen &4&lGWEN&c: Moved too quickly. Speedhack, flight"

derp:
   enabled: true
   thresholds:
      1: "ba kick {player} gwen &4&lGWEN&c: Dont derp hack"

knockback:
   enabled: false
   tick_delay: 9
   add_ping: true
   max_ping: 500
   min_knockback_dist: 0.01
   min_knockback_time: 2
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for Anti-Knockback (ping = {ping}, tps = {tps})"
      25: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      50: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      100: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      125: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      150: "ba ban {player} gwen &4&lGWEN&c: Using antiknockback"

noswing:
   enabled: true
   thresholds:
      20: "aacstaffnotify {player} in {world} is not swinging their arm (ping = {ping}, tps = {tps})"
      50: "ba kick {player} gwen &4&lGWEN&c: Not swinging arm"
      100: "ba ban {player} gwen &4&lGWEN&c: Using noswing"

regen:
   enabled: true
   cancel_regen: true
   min_regen_delay: 3600
   min_satiated_delay: 450
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for Regen (ping = {ping}, tps = {tps})"
      15: "ba kick {player} gwen &4&lGWEN&c: Regenerating health too quickly"
      30: "ba kick {player} gwen &4&lGWEN&c: Regenerating health too quickly"
      50: "ba kick {player} gwen &4&lGWEN&c: Regenerating health too quickly"
      100: "ba ban {player} gwen &4&lGWEN&c: Regenerating health too quickly"

killaura:
   enabled: true
   check_chance: 100
   check_delay: 3
   listen_delay: 6
   min_dist: 1.2
   duration: 20
   weight: 4
   max_diff: 0.11
   max_reach: 4.5
   thresholds:
      25: "aacstaffnotify {player} in {world} is suspected for Killaura (Normal) (ping = {ping}, tps = {tps})"
      100: "ba kick {player} gwen &4&lGWEN&c: Killaura is not allowed"
      250: "ba kick {player} gwen &4&lGWEN&c: Killaura is not allowed"
      500: "ba ban {player} gwen &4&lGWEN&c: Hacking - Killaura is not allowed"

heuristics:
   enabled: true
   min_confidence: 50
   thresholds: {}

nofall:
   enabled: true
   required_velocity: -0.2
   deal_damage: true
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for NoFall hacks (ping = {ping}, tps = {tps})"
      25: "ba kick {player} gwen &4&lGWEN&c: Hacking - Taking No Fall damage"
      50: "ba kick {player} gwen &4&lGWEN&c: Hacking - Taking No Fall damage"
      75: "ba kick {player} gwen &4&lGWEN&c: Hacking - Taking No Fall damage"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Taking No Fall damage"

jesus:
   enabled: true
   teleport: true
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for Jesus hacks (ping = {ping}, tps = {tps})"
      25: "aacstaffnotify {player} in {world} is very likely to be using Jesus hacks"
      50: "ba kick {player} gwen &4&lGWEN&c: Hacking - Walking on water?"
      75: "ba kick {player} gwen &4&lGWEN&c: Hacking - Walking on water?"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Jesus hacks"

phase:
   enabled: true
   exclude:
   # Incorrect hitboxes in 1.8 servers
    - "ANVIL"
    - "CHEST"
    - "ENDER_CHEST"
    - "TRAPPED_CHEST"
    - "SOIL"
   # Entity hitboxes
    - "AIR"
    - "STATIONARY_WATER"
    - "WATER"
    - "STATIONARY_LAVA"
    - "LAVA"
   # Protocol hack hitboxes
    - "WATER_LILY"
   # Moving pistons
    - "PISTON_MOVING_PIECE"
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for Phase (ping = {ping}, tps = {tps})"
      30: "aacstaffnotify {player} in {world} is suspected for Phase #2 (ping = {ping}, tps = {tps})"
      50: "ba kick {player} gwen &4&lGWEN&c: Hacking - Phase"
      75: "ba kick {player} gwen &4&lGWEN&c: Hacking - Phase"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Phase"
fastuse:
   enabled: true
   ms_to_use: 1200
   thresholds:
      2: "aacstaffnotify {player} in {world} is suspected for FastEat hacks (ping = {ping}, tps = {tps})"
      5: "ba kick {player} gwen &4&lGWEN&c: Hacking - Using items too quickly"
      10: "ba kick {player} gwen &4&lGWEN&c: Hacking - Using items too quickly"
      15: "ba kick {player} gwen &4&lGWEN&c: Hacking - Using items too quickly"
      25: "ba kick {player} gwen &4&lGWEN&c: Hacking - Using items too quickly"

fastbreak:
   enabled: true
   let_ticks: 2
   cancel_break: true
   check_delay: true
   cancel_vl: 1
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for FastBreak hacks (ping = {ping}, tps = {tps})"
      15: "ba kick {player} gwen &4&lGWEN&c: Hacking - Breaking blocks too fast"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Breaking blocks too fast"
      500: "ba kick {player} gwen &4&lGWEN&c: Hacking - Breaking blocks too fast"

fastplace:
   enabled: true
   max_place_per_second: 10
   cancel_place: true
   cancel_vl: 2
   thresholds:
      10: "aacstaffnotify {player} in {world} is suspected for FastBreak hacks (ping = {ping}, tps = {tps})"
      15: "ba kick {player} gwen &4&lGWEN&c: Hacking - Placing blocks too fast"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Placing blocks too fast"
      500: "ba kick {player} gwen &4&lGWEN&c: Hacking - Placing blocks too fast"

nuker:
   enabled: true
   max_breaks_per_second: 40
   vl_divisor: 41
   thresholds:
      5: "aacstaffnotify {player} in {world} is suspected for Nuker (ping = {ping}, tps = {tps})"
      10: "ba kick {player} gwen &4&lGWEN&c: Hacking - Suspected for nuker"
      25: "ba kick {player} gwen &4&lGWEN&c: Hacking - Suspected for nuker"
      50: "ba kick {player} gwen &4&lGWEN&c: Hacking - Suspected for nuker"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Suspected for nuker"

interact:
   enabled: true
   cancel_liquids: true
   cancel_ghost_block: true
   cancel_dead: true
   cancel_item_attack: true
   cancel_ghost_attack: true
   cancel_vl_interact: 5
   cancel_vl_place: 5
   cancel_vl_break: 0

   thresholds:
      10: "aacstaffnotify {player} in {world} is interacting suspiciously (ghosthand) (ping = {ping}, tps = {tps})"
      25: "ba kick {player} gwen &4&lGWEN&c: interacting suspiciously (ghosthand) #2"
      50: "ba kick {player} gwen &4&lGWEN&c: interacting suspiciously (ghosthand) #3"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - Ghosthand"


velocity:
   enabled: true
   check_length: 15
   max_tp_dist: 3.0
   min_vl: 5
   vl_normal: 2
   vl_no_packet: 0
   thresholds:
      5: "aacstaffnotify {player} in {world} seems to be ignoring velocity"
      10: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      25: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      50: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      75: "ba kick {player} gwen &4&lGWEN&c: Not taking knockback"
      100: "ba kick {player} gwen &4&lGWEN&c: Hacking - AntiKnockback"

spam:
   enabled: true
   whitelist:
     - "lol"
     - "hello"
     - "okay"
     - "hi"
     - "welcome"
     - "wb"
   
   message_limit: 4
   chat_speed: 10
   thresholds:
      5: "aacstaffnotify {player} in {world} is probably spamming"
      10: "ba kick {player} gwen &4&lGWEN&c: Stop spamming, you sad person"
      15: "ba kick {player} gwen &4&lGWEN&c: Spamming"
      25: "ba kick {player} gwen &4&lGWEN&c: Spamming"
      50: "ba kick {player} gwen &4&lGWEN&c: Spamming"

move:
   enabled: true
   min_balance: -50
   cancel_threshold: 5
   reset_level: -1
   balance_cap: 10
   decay: 25
   thresholds:
      200: "aacstaffnotify {player} in {world} is sending unusual movement information (ping = {ping}, tps = {tps})"
      500: "ba kick {player} gwen &4&lGWEN&c: Sending unusual movement packets"
      750: "ba kick {player} gwen &4&lGWEN&c: Sending unusual movement packets"
      1000: "ba kick {player} gwen &4&lGWEN&c: Sending unusual movement packets"

ban_threshold: 50
ban_command: "ba ban {player} gwen &4&lGWEN&c: Hacking/breaking rules - Warned by staff too many times"
kick_ticks: 120
combat_time: 50
kill_loggers: true
log_file: true
aackick_broadcast: true
usetps: true
#verbose: false
#log_console: false
